#!/bin/sh
export PATH=$PATH:~/Qt/5.13.0/gcc_64/bin
sudo apt-get install qt5-default
qmake -o Makefile scapes.pro > buildOut.txt
make > makeOut.txt
echo Build completed successfully
rm -rf buildOut.txt makeOut.txt
